title = "annovarR download configuration file (Using BioInstaller)"

[avsnp]
source_url = "http://bioinfo.rjh.com.cn/download/annovarR/humandb/{{version}}.sqlite"
decompress = false
version_newest = "hg19_avsnp147"
version_available = ["hg19_avsnp138", "hg19_avsnp142", "hg19_avsnp144", "hg19_avsnp147"]

[cosmic]
source_url = "http://bioinfo.rjh.com.cn/download/annovarR/humandb/{{version}}.sqlite"
decompress = false
version_newest = "hg19_cosmic81"
version_available = ["hg19_cosmic70", "hg19_cosmic81"]

[1000g]
source_url = [
              "http://bioinfo.rjh.com.cn/download/annovarR/humandb/@>@str_replace('{{version}}', '-.*', '')@<@_AMR.sites.@>@str_replace('{{version}}', '.*-', '')@<@.sqlite",
              "http://bioinfo.rjh.com.cn/download/annovarR/humandb/@>@str_replace('{{version}}', '-.*', '')@<@_ALL.sites.@>@str_replace('{{version}}', '.*-', '')@<@.sqlite",
              "http://bioinfo.rjh.com.cn/download/annovarR/humandb/@>@str_replace('{{version}}', '-.*', '')@<@_AFR.sites.@>@str_replace('{{version}}', '.*-', '')@<@.sqlite",
              "http://bioinfo.rjh.com.cn/download/annovarR/humandb/@>@str_replace('{{version}}', '-.*', '')@<@_EAS.sites.@>@str_replace('{{version}}', '.*-', '')@<@.sqlite",
              "http://bioinfo.rjh.com.cn/download/annovarR/humandb/@>@str_replace('{{version}}', '-.*', '')@<@_EUR.sites.@>@str_replace('{{version}}', '.*-', '')@<@.sqlite",
              "http://bioinfo.rjh.com.cn/download/annovarR/humandb/@>@str_replace('{{version}}', '-.*', '')@<@_SAS.sites.@>@str_replace('{{version}}', '.*-', '')@<@.sqlite"]
decompress = [false, false, false, false, false, false]
version_newest = "hg19-2015_08"
version_available = ["hg19-2015_08", "hg19-2014_10"]

[radar]
source_url = "http://bioinfo.rjh.com.cn/download/annovarR/humandb/{{version}}.sqlite"
decompress = false
version_newest = "hg19_RADAR2"
version_available = ["hg19_RADAR2"]

[darned]
source_url = "http://bioinfo.rjh.com.cn/download/annovarR/humandb/{{version}}.sqlite"
decompress = false
version_newest = "hg19_DARNED"
version_available = ["hg19_DARNED"]

[normal_pool]
source_url = "http://bioinfo.rjh.com.cn/download/annovarR/humandb/@>@str_replace('{{version}}', '_', '_normal')@<@.txt"
decompress = false
version_newest = "hg19_2016sih_wes_ball"
version_available = ['hg19_2016sih_wes_ball', 'hg19_2016sih_wes_tall', '2016sih_wes_nkt', '2016sih_wgs_nkt', '2016sih_wgs_dlbcl']

[clinvar]
source_url = "http://bioinfo.rjh.com.cn/download/annovarR/humandb/{{version}}.sqlite"
decompress = false
version_newest = "hg19_clinvar_20170130"
version_available = ["hg19_clinvar_20170130"]

[intervar]
source_url = "http://bioinfo.rjh.com.cn/download/annovarR/humandb/{{version}}.sqlite"
decompress = false
version_newest = "hg19_intervar_20170202"
version_available = ["hg19_intervar_20170202"]
